
name: Release NPM Package

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build_ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-binary
          path: target/release/atomic-styles

  build_macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 
      - name: Build
        run: cargo build --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: osx-binary
          path: target/release/atomic-styles

  build_windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --release
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-binary
          path: target/release/atomic-styles.exe

  publish_npm_package:
    needs: [build_ubuntu, build_macos, build_windows]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: craigfay
      - uses: actions/download-artifact@v2
        with:
          path: dist
      - name: Grant Permissions
        run: chmod +x dist/*
      - name: List Dir
        run: ls -R
      - name: Preview Publish
        run: npm pack
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}